# Generated by Django 4.2.27 on 2026-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scadenza'),
        ),
    ]
