# Generated by Django 4.2.27 on 2026-01-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_created_at_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='property',
            name='owner_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.agent'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
