# Generated by Django 4.2.27 on 2026-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_propertyimage_options_property_owner_agent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['position', '-is_primary', 'id']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_agent',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
