# Generated by Django 4.2.27 on 2026-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
