# Generated by Django 4.2.27 on 2026-01-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='properties/%Y/%m/attachments/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.property')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
