# Generated by Django 4.2.27 on 2026-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_propertyattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
